### ISSUE TITLE
Too many connections

### ISSUE THREAD

**Issue by gvermillion** [simfection/simfection#2]
# Overview

Occasionally, an agent may have the attribute`max_connections=N`, but once the connection engine runs, it has `num_connections>N`. Anecdotally, the observed differences were +<4 and only for a few agents. So, not a big discrepancy, but something that shouldn’t be happening. 

This may be happening because of the recursive pattern. Perhaps `num_connections` to not being updated before `_available_to_connect` is called. 

# To Do

- Test frequency of problem of many runs
- Fix if bad results
- Create unit test

**Comment by alexanderogle** [comment]
Wrote two unit tests on branch `feature/test_connection_engine`, see file `test_connection_engine.py`. Currently those tests are failing because:
a) an agent has a max_connection of 0, but has 1 connection in their connection list
b) an agent has a repeat connection in their connection list

I feel like (b) shouldn't be WAI, since that might be another round of rolling the dice to see if they infect / are infected by that connection.

**Comment by gvermillion** [comment]
Closing this because not an issue with C++ code.
